# -*- coding: utf-8 -*-
"""fitri ananda syabrina

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_gVbOkjD_1nTMhH-d6nUDQ1uJeY8gnt-
"""

from itertools import combinations
while True:
  x = int(input("x = "))
  if x > 1:
    break
  else:
    print("Masukkan bilangan bulat lebih dari 1")

#point a
faktor = 0
for i in range(1,x+1): # i adalah angka dari 1 sampai x
  if  x % i == 0:
    faktor += 1
if faktor > 2:
  print(x,"bilangan komposit maka point a terpenuhi")
else:
  print(x,"bilangan prima maka point a tidak terpenuhi")


#point b
a = []
for i in range(1,x):
  if x % i == 0:
    a.append(i)
print("Pembagi:",a)

n = len(a)
jumlah = 0
for i in range(n):
  jumlah += a[i]

if jumlah > x:
  print(jumlah,">",x,"maka point b terpenuhi")
else:
  print(jumlah,"<=",x,"maka point b tidak terpenuhi")

#point c
if jumlah > x:
  cek = False
  kombinasi = []
  for i in range(1, len(a)+1):
    for subset in combinations(a, i):
      if sum(subset) == x:
        kombinasi = subset
        cek = True
        break
    if cek:
      break

  if not cek:
    print("tidak ada kombinasi angka sehingga point c memenuhi")
    print("Maka,",x,"bilangan aneh")
  else:
    print("ada kombinasi", kombinasi,"sehingga point c tidak memenuhi")
    print("Maka,",x,"bukan bilangan aneh")
else:
  print("karena",jumlah,"<=",x,", point c tidak terpenuhi")
  print("Maka,",x,"bukan bilangan aneh")